<?php
    require('config.php');
    $strUserSessionID = $_POST['strUserSessionID'];
    $intMatch = $_POST['intMatch'];
    $intTeamScouting = $_POST['intTeamScouting'];
    $strScoutingPosition = $_POST['strScoutingPosition'];
    $strTarmacStartingPosition = $_POST['strTarmacStartingPosition'];
    $blnAutoTarmacTaxi = $_POST['blnAutoTarmacTaxi'];
    $intAutoUpperHub = $_POST['intAutoUpperHub'];
    $intAutoLowerHub = $_POST['intAutoLowerHub'];
    $intTeleOpUpperHub = $_POST['intTeleOpUpperHub'];
    $intTeleOpLowerHub = $_POST['intTeleOpLowerHub'];
    $blnTeleOpShootsBalls = $_POST['blnTeleOpShootsBalls'];
    $blnTeleOpPlaysDefense = $_POST['blnTeleOpPlaysDefense'];
    $strEndGameClimbing = $_POST['strEndGameClimbing'];
    $blnMoreQuintet = $_POST['blnMoreQuintet'];
    $blnMoreThan16 = $_POST['blnMoreThan16'];
    $moreWinMatch = $_POST['moreWinMatch'];
    $intAutoMissed = $_POST['intAutoMissed'];
    $intTeleMissed = $_POST['intTeleMissed'];
    $blnAutoBallPickUp = $_POST['blnAutoBallPickUp'];
    $swPlayedMatch = $_POST['swPlayedMatch'];
    //$teleRobotPlayDefense = $_POST['teleRobotPlayDefense'];
    $moreClimbRP = $_POST['moreClimbRP'];
    $moreFlipped = $_POST['moreFlipped'];
    $moreBricked = $_POST['moreBricked'];

    $strUserSessionID = strip_tags($strUserSessionID);
    $intMatch = strip_tags($intMatch);
    $intTeamScouting = strip_tags($intTeamScouting);
    $strScoutingPosition = strip_tags($strScoutingPosition);
    $strTarmacStartingPosition = strip_tags($strTarmacStartingPosition);
    $blnAutoTarmacTaxi = strip_tags($blnAutoTarmacTaxi);
    $intAutoUpperHub = strip_tags($intAutoUpperHub);
    $intAutoLowerHub = strip_tags($intAutoLowerHub);
    $intTeleOpUpperHub = strip_tags($intTeleOpUpperHub);
    $intTeleOpLowerHub = strip_tags($intTeleOpLowerHub);
    $blnTeleOpShootsBalls = strip_tags($blnTeleOpShootsBalls);
    $blnTeleOpPlaysDefense = strip_tags($blnTeleOpPlaysDefense);
    $strEndGameClimbing = strip_tags($strEndGameClimbing);
    $blnMoreQuintet = strip_tags($blnMoreQuintet);
    $blnMoreThan16 = strip_tags($blnMoreThan16);
    $moreWinMatch = strip_tags($moreWinMatch);
    $intAutoMissed = strip_tags($intAutoMissed);
    $intTeleMissed = strip_tags($intTeleMissed);
    $blnAutoBallPickUp = strip_tags($blnAutoBallPickUp);
    $swPlayedMatch = strip_tags($swPlayedMatch);
    //$teleRobotPlayDefense = strip_tags($teleRobotPlayDefense);
    $moreClimbRP = strip_tags($moreClimbRP);
    $moreFlipped = strip_tags($moreFlipped);
    $moreBricked = strip_tags($moreBricked);
  
    echo addObservation($strUserSessionID,$intMatch,$intTeamScouting,$strScoutingPosition,$strTarmacStartingPosition,$blnAutoTarmacTaxi,$intAutoUpperHub,$intAutoLowerHub,$intTeleOpUpperHub,$intTeleOpLowerHub,$blnTeleOpShootsBalls,$blnTeleOpPlaysDefense,$strEndGameClimbing,$blnMoreQuintet,$blnMoreThan16,$moreWinMatch,$intAutoMissed,$intTeleMissed,$blnAutoBallPickUp,$swPlayedMatch,$moreClimbRP,$moreFlipped,$moreBricked);
?>